# Generated by Django 3.2.24 on 2024-04-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
