# Generated by Django 3.2.24 on 2024-05-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_question_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Pysintax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=3000)),
            ],
        ),
    ]
