# Generated by Django 3.2.24 on 2024-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_djangoinfo_pysintax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
