# Generated by Django 3.2.24 on 2024-06-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_studying_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pysintax',
            new_name='Pysyntax',
        ),
    ]
