version: "3.9"

services:
  postgres:
    image: postgres:14.3-alpine 
    volumes:
      - ./django-postgres/pysite:/app/pysite
    env_file:
      - env
    environment:
      COMPOSE_HTTP_TIMEOUT: 3600
      POSTGRES_DB: postgres
      POSTGRES_USER: alen
      POSTGRES_PASSWORD: alen2007!
      DB_SERVICE: 127.0.0.1
      DB_PORT: 5432
    expose:
      - 5432
    ports:
      - 5436:5432
    networks:
      - pgnet

  web:
    image: api:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000cd
    ports:
      - "8000:8000"
    volumes:
      - .:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEPLOYMENT: api
      COMPOSE_HTTP_TIMEOUT: 3600
      LC_CTYPE: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    env_file: env
    command: bash -c 'python3 pysite/manage.py runserver 0.0.0.0:8000'
    networks:
      - pgnet  

volumes:
  pgdata:
  esdata1:
    driver: local

networks:
  pgnet: